/**
 * Bakes the cast's portraits into src/lib/cast.ts.
 *
 * DiceBear draws them, but it draws them at *build* time and we keep the
 * result in the repo: the pictures are part of the design, not something we
 * want quietly changing when a dependency does. Run this again only if you
 * want to redraw somebody.
 *
 *   bun scripts/gen-cast.mjs
 */
import { createAvatar } from "@dicebear/core";
import { bigSmile } from "@dicebear/collection";
import { writeFileSync } from "node:fs";

const CAST = [
  {
    id: "wren",
    name: "Wren",
    role: "asks the why",
    opts: { seed: "wren", eyes: ["starstruck"], mouth: ["openedSmile"],
            hair: ["curlyBob"], hairColor: ["238d80"], skinColor: ["e2ba87"],
            accessoriesProbability: 0 },
  },
  {
    id: "basil",
    name: "Basil",
    role: "reads the small print",
    opts: { seed: "basil", eyes: ["normal"], mouth: ["awkwardSmile"],
            hair: ["bowlCutHair"], hairColor: ["3a1a00"], skinColor: ["c99c62"],
            accessories: ["glasses"], accessoriesProbability: 100 },
  },
  {
    id: "juno",
    name: "Juno",
    role: "would rather just try it",
    opts: { seed: "juno", eyes: ["cheery"], mouth: ["teethSmile"],
            hair: ["froBun"], hairColor: ["d56c0c"], skinColor: ["8c5a2b"],
            accessoriesProbability: 0 },
  },
  {
    id: "moss",
    name: "Moss",
    role: "has been stuck here before",
    opts: { seed: "moss", eyes: ["sleepy"], mouth: ["awkwardSmile"],
            hair: ["bunHair"], hairColor: ["605de4"], skinColor: ["ffe4c0"],
            accessoriesProbability: 0 },
  },
];

const parts = CAST.map((c) => {
  const svg = createAvatar(bigSmile, { size: 96, ...c.opts })
    .toString()
    .replace(/\s+/g, " ")
    .replace(/<svg /, '<svg class="portrait__svg" aria-hidden="true" focusable="false" ');
  return `  ${c.id}: {\n    name: ${JSON.stringify(c.name)},\n    role: ${JSON.stringify(c.role)},\n    svg: ${JSON.stringify(svg)},\n  },`;
}).join("\n");

writeFileSync(
  "src/lib/cast-art.ts",
  `/* GENERATED by scripts/gen-cast.mjs — edit that, not this. */\n` +
  `/* Portraits: "Custom Avatar" by Ashley Seo, CC BY 4.0, drawn by DiceBear. */\n\n` +
  `export const CAST_ART: Record<string, { name: string; role: string; svg: string }> = {\n${parts}\n};\n`,
);
console.log("wrote src/lib/cast-art.ts");
